// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-ve_gckmqfeigmKahijDU3aM9lG47NME',
    appId: '1:265312952465:web:f187adc4cb8b7e591e1f30',
    messagingSenderId: '265312952465',
    projectId: 'smart-urban-system',
    authDomain: 'smart-urban-system.firebaseapp.com',
    storageBucket: 'smart-urban-system.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgbIRnMKvn9SDgqRu4SUJbUzr9fO1VF3g',
    appId: '1:265312952465:android:a67543a6010da7dd1e1f30',
    messagingSenderId: '265312952465',
    projectId: 'smart-urban-system',
    storageBucket: 'smart-urban-system.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAYpEIqORgYY-p7YTtdNb1ytpLiqDYutg',
    appId: '1:265312952465:ios:f10ef8e75598bbac1e1f30',
    messagingSenderId: '265312952465',
    projectId: 'smart-urban-system',
    storageBucket: 'smart-urban-system.firebasestorage.app',
    iosBundleId: 'com.example.smartUrbanWasteCollectionSystem',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAYpEIqORgYY-p7YTtdNb1ytpLiqDYutg',
    appId: '1:265312952465:ios:f10ef8e75598bbac1e1f30',
    messagingSenderId: '265312952465',
    projectId: 'smart-urban-system',
    storageBucket: 'smart-urban-system.firebasestorage.app',
    iosBundleId: 'com.example.smartUrbanWasteCollectionSystem',
  );
}
